# superuser permission
sudo: required
services:
  - docker

before_install:
  - docker build -t orenkole/grider-docker -f Dockerfile.dev .

script:
  - docker run orenkole/grider-docker npm run test -- --coverage
