sudo: required
services:
  - docker

before_install:
  # ./client - build context
  - docker build -t orenkole/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run orenkole/react-test npm test -- --coverage

after_success:
  - docker build -t orenkole/multi-client ./client
  - docker build -t orenkole/multi-nginx ./nginx
  - docker build -t orenkole/multi-server ./server
  - docker build -t orenkole/multi-worker ./worker
