version: "3"
services:
  postgres:
    image: "postgres:latest"
  redis:
    image: "redis:5-alpine3.15"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      # don't create link to node_modules. Don't redirect node_modules
      - /app/node_modules
      # link everything else from 'server' to 'app'
      - ./server:/app
    environment:
      # value takes from services:
      - REDIS_HOST=redis
      # port from documentation (but can be configured)
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
